spring:
  datasource:
    #    初始化远程容器数据库,通过本地3308端口映射到远程3306端口
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/res_cloud?serverTimezone=UTC
    username: root
    password: 1234
  sql:
    init:
      schema-locations:
        -classpath*: schema-all.sql
      data-locations:
        -classpath*: data-all.sql
      username: root
      password: 1234
      mode: always